---
- hosts: all
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: configure nginx
    copy:
      src: ../resources/nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: reload nginx service
    service:
      name: nginx
      state: reloaded
