server:
  port: 8084

spring:
  application:
    name: account-token-aggregation

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true   
